# ===================================================================
# ANALYSIS OUTPUT - CAPEX-SEPARATE MODEL
# Compatible with NEW_model_CAPEX_separate.R after CAPEX matrices
# (A_capex_dom_tech / A_capex_imp_tech) are included in saved results.
# ===================================================================

rm(list = ls())
options(scipen = 999)

# ===================================================================
# 1. LOAD MODEL RESULTS
# ===================================================================

RESULTS_FILE <- "model_results_CAPEX_separate.rds"
OUTPUT_DIR   <- "analysis_outputs"


dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)

results <- readRDS(RESULTS_FILE)

# ===================================================================
# 2. BASIC SETTINGS AND FUEL GROUPS
# ===================================================================

BIO          <- results$metadata$BIO
NONBIO       <- results$metadata$NONBIO
sector_names <- results$metadata$sector_names

benchmark_years <- c("2030", "2035", "2040")
scenario_names  <- c("S1", "S2", "S3")
all_scenarios   <- c("REF", scenario_names)

BIOFUEL_SECTORS <- c(
  conv_biodiesel    = 12,
  adv_biodiesel     = 13,
  conv_biogasoline  = 14,
  adv_biogasoline   = 15,
  conv_bio_kerosene = 16,
  adv_bio_kerosene  = 17,
  adv_bio_hfo       = 18,
  RFNBOs            = 19,
  adv_biogas        = 33
)

ADV_BIO <- unname(
  BIOFUEL_SECTORS[
    c(
      "adv_biodiesel",
      "adv_biogasoline",
      "adv_bio_kerosene",
      "adv_bio_hfo",
      "adv_biogas"
    )
  ]
)

CONV_BIO <- unname(
  BIOFUEL_SECTORS[
    c(
      "conv_biodiesel",
      "conv_biogasoline",
      "conv_bio_kerosene"
    )
  ]
)

RFNBO_SECTOR <- unname(BIOFUEL_SECTORS["RFNBOs"])

biofuel_names <- setNames(
  names(BIOFUEL_SECTORS),
  as.character(BIOFUEL_SECTORS)
)

fuel_group_by_sector <- setNames(
  rep(NA_character_, length(BIOFUEL_SECTORS)),
  as.character(unname(BIOFUEL_SECTORS))
)

fuel_group_by_sector[as.character(CONV_BIO)] <- "conventional"
fuel_group_by_sector[as.character(ADV_BIO)]  <- "advanced"
fuel_group_by_sector[as.character(RFNBO_SECTOR)] <- "RFNBO"

stopifnot(
  setequal(BIO, unname(BIOFUEL_SECTORS)),
  length(BIO) + length(NONBIO) == length(sector_names),
  all(benchmark_years %in% names(results)),
  "dynamic" %in% names(results)
)

dynamic_results <- results$dynamic
annual_years     <- dynamic_results$REF$years

# ===================================================================
# 3. HELPERS
# ===================================================================

safe_ratio <- function(num, den, tol = 1e-12) {
  ifelse(abs(den) > tol, num / den, NA_real_)
}

get_endpoint <- function(year, scenario) {
  results[[as.character(year)]][[scenario]]
}

get_fuel_name <- function(sector_id) {
  unname(biofuel_names[as.character(sector_id)])
}

get_fuel_group <- function(sector_id) {
  unname(fuel_group_by_sector[as.character(sector_id)])
}

# Direct recurrent domestic demand generated by BIO production.
get_domestic_recurrent_demand <- function(endpoint) {
  endpoint$A_dom_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}

# Direct domestic FEEDSTOCK demand generated by BIO production.
get_domestic_feedstock_demand <- function(endpoint) {

  endpoint$A_feed_dom_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}


# Direct domestic OPEX demand generated by BIO production.
get_domestic_opex_demand <- function(endpoint) {

  endpoint$A_opex_dom_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}


# Direct recurrent imported-input demand generated by BIO production.
get_imported_recurrent_demand <- function(endpoint) {
  endpoint$A_imp_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}

get_imported_feedstock_demand <- function(endpoint) {

  endpoint$A_feed_imp_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}


get_imported_opex_demand <- function(endpoint) {

  endpoint$A_opex_imp_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}


# Direct domestic CAPEX demand level K_t generated by BIO production.
get_domestic_capex_level_from_coefficients <- function(endpoint) {
  endpoint$A_capex_dom_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}

# Direct imported CAPEX demand level generated by BIO production.
get_imported_capex_level_from_coefficients <- function(endpoint) {
  endpoint$A_capex_imp_tech[, BIO, drop = FALSE] %*%
    endpoint$X_bio[BIO]
}

# ===================================================================
# 4. PRE-FLIGHT CHECKS
# ===================================================================

# Fields required for ALL endpoints, including REF
required_endpoint_fields_common <- c(
  "X",
  "GVA",
  "A_dom_tech",
  "A_imp_tech",
  "A_capex_dom_tech",
  "A_capex_imp_tech",
  "X_bio",
  "Y_imp_FCE",
  "exports",
  "GFCF_capex_level",
  "GFCF_capex_delta",
  "CAPEX_imp_leakage"
)

# Additional fields required ONLY for S1/S2/S3
# because the Feedstock/OPEX analysis is scenario-internal
required_endpoint_fields_channels <- c(
  "A_feed_dom_tech",
  "A_feed_imp_tech",
  "A_opex_dom_tech",
  "A_opex_imp_tech"
)

for (year in benchmark_years) {
  year_results <- results[[year]]

  stopifnot(all(all_scenarios %in% names(year_results)))

  for (scenario_name in all_scenarios) {
    endpoint <- year_results[[scenario_name]]

required_fields_current <- required_endpoint_fields_common

if (scenario_name %in% scenario_names) {
  required_fields_current <- c(
    required_fields_current,
    required_endpoint_fields_channels
  )
}

missing_fields <- setdiff(
  required_fields_current,
  names(endpoint)
)

    if (length(missing_fields) > 0) {
      stop(
        paste0(
          "Missing field(s) in ", year, "/", scenario_name, ": ",
          paste(missing_fields, collapse = ", "),
          ". Add A_capex_dom_tech and A_capex_imp_tech to the model result object, rerun the model, and save a fresh model_results_CAPEX_separate.rds."
        )
      )
    }

stopifnot(
  length(endpoint$X) == length(sector_names),
  length(endpoint$GVA) == length(sector_names),
  length(endpoint$X_bio) == length(sector_names),

  !anyNA(endpoint$X),
  !anyNA(endpoint$GVA),
  !anyNA(endpoint$X_bio[BIO]),

  !anyNA(endpoint$A_dom_tech),
  !anyNA(endpoint$A_imp_tech),

  !anyNA(endpoint$A_capex_dom_tech),
  !anyNA(endpoint$A_capex_imp_tech)
)

# Feedstock/OPEX fields are only needed for S1/S2/S3
if (scenario_name %in% scenario_names) {

  stopifnot(
    !anyNA(endpoint$A_feed_dom_tech),
    !anyNA(endpoint$A_feed_imp_tech),
    !anyNA(endpoint$A_opex_dom_tech),
    !anyNA(endpoint$A_opex_imp_tech)
  )
}

    # CAPEX level stored by the model must match the level reconstructed
    # from the stored CAPEX coefficients and BIO output.
    reconstructed_dom_capex <-
      as.numeric(get_domestic_capex_level_from_coefficients(endpoint))

    reconstructed_imp_capex <-
      as.numeric(get_imported_capex_level_from_coefficients(endpoint))

    stopifnot(
      isTRUE(
        all.equal(
          reconstructed_dom_capex[NONBIO],
          endpoint$GFCF_capex_level[NONBIO],
          tolerance = 1e-8
        )
      ),
      isTRUE(
        all.equal(
          reconstructed_imp_capex[NONBIO],
          endpoint$CAPEX_imp_leakage[NONBIO],
          tolerance = 1e-8
        )
      )
    )

if (scenario_name %in% scenario_names) {

  stopifnot(

    isTRUE(
      all.equal(
        endpoint$A_dom_tech[, BIO, drop = FALSE],
        endpoint$A_feed_dom_tech[, BIO, drop = FALSE] +
          endpoint$A_opex_dom_tech[, BIO, drop = FALSE],
        tolerance = 1e-10
      )
    ),

    isTRUE(
      all.equal(
        endpoint$A_imp_tech[, BIO, drop = FALSE],
        endpoint$A_feed_imp_tech[, BIO, drop = FALSE] +
          endpoint$A_opex_imp_tech[, BIO, drop = FALSE],
        tolerance = 1e-10
      )
    )
  )
}
  }
}

# Complete annual paths must be aligned.
stopifnot(
  identical(dynamic_results$REF$years, 2023:2040),
  identical(dynamic_results$S1$years, dynamic_results$REF$years),
  identical(dynamic_results$S2$years, dynamic_results$REF$years),
  identical(dynamic_results$S3$years, dynamic_results$REF$years)
)

# Reference path must remain stationary by construction.
ref_X_2023   <- dynamic_results$REF$X[1, ]
ref_GVA_2023 <- dynamic_results$REF$GVA[1, ]

stopifnot(
  max(abs(dynamic_results$REF$X -
            matrix(ref_X_2023,
                   nrow = length(annual_years),
                   ncol = length(sector_names),
                   byrow = TRUE))) < 1e-8,
  max(abs(dynamic_results$REF$GVA -
            matrix(ref_GVA_2023,
                   nrow = length(annual_years),
                   ncol = length(sector_names),
                   byrow = TRUE))) < 1e-8
)

# ===================================================================
# 5. AGGREGATE OUTPUT AND GVA EFFECTS: SCENARIO VS REF
# ===================================================================

calculate_macro_summary <- function(year_results, year) {
  REF <- year_results$REF

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- year_results[[scenario_name]]

      delta_X   <- scenario$X   - REF$X
      delta_GVA <- scenario$GVA - REF$GVA

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,

        ref_total_output = sum(REF$X),
        scenario_total_output = sum(scenario$X),
        total_output_change = sum(delta_X),
        total_output_change_pct =
          100 * safe_ratio(sum(delta_X), sum(REF$X)),

        bio_output_change = sum(delta_X[BIO]),
        nonbio_output_change = sum(delta_X[NONBIO]),

        ref_total_GVA = sum(REF$GVA),
        scenario_total_GVA = sum(scenario$GVA),
        total_GVA_change = sum(delta_GVA),
        total_GVA_change_pct =
          100 * safe_ratio(sum(delta_GVA), sum(REF$GVA)),

        bio_GVA_change = sum(delta_GVA[BIO]),
        nonbio_GVA_change = sum(delta_GVA[NONBIO])
      )
    }
  )

  do.call(rbind, out)
}

macro_summary_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      calculate_macro_summary(results[[year]], year)
    }
  )
)
rownames(macro_summary_all) <- NULL

# Convenience benchmark tables
macro_summary_2030 <- subset(macro_summary_all, year == 2030)
macro_summary_2035 <- subset(macro_summary_all, year == 2035)
macro_summary_2040 <- subset(macro_summary_all, year == 2040)

# ===================================================================
# 6. PAIRWISE SCENARIO COMPARISONS: OUTPUT AND GVA
# ===================================================================

calculate_pairwise_macro <- function(year_results, year) {
  comparisons <- list(
    "S2-S1" = c("S2", "S1"),
    "S3-S1" = c("S3", "S1"),
    "S3-S2" = c("S3", "S2")
  )

  out <- lapply(
    names(comparisons),
    function(comparison_name) {
      high_name <- comparisons[[comparison_name]][1]
      low_name  <- comparisons[[comparison_name]][2]

      high <- year_results[[high_name]]
      low  <- year_results[[low_name]]

      delta_X   <- high$X   - low$X
      delta_GVA <- high$GVA - low$GVA

      data.frame(
        year = as.integer(year),
        comparison = comparison_name,
        total_output_difference = sum(delta_X),
        bio_output_difference = sum(delta_X[BIO]),
        nonbio_output_difference = sum(delta_X[NONBIO]),
        total_GVA_difference = sum(delta_GVA),
        bio_GVA_difference = sum(delta_GVA[BIO]),
        nonbio_GVA_difference = sum(delta_GVA[NONBIO])
      )
    }
  )

  do.call(rbind, out)
}

pairwise_macro_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_pairwise_macro(results[[year]], year)
  )
)
rownames(pairwise_macro_all) <- NULL

# ===================================================================
# 7. ANNUAL OUTPUT AND GVA PATHS: 2023-2040
# ===================================================================

calculate_annual_macro_path <- function(dynamic_results) {
  REF <- dynamic_results$REF

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- dynamic_results[[scenario_name]]

      delta_X   <- scenario$X   - REF$X
      delta_GVA <- scenario$GVA - REF$GVA

      data.frame(
        year = scenario$years,
        scenario = scenario_name,

        ref_total_output = rowSums(REF$X),
        scenario_total_output = rowSums(scenario$X),
        total_output_change = rowSums(delta_X),
        bio_output_change = rowSums(delta_X[, BIO, drop = FALSE]),
        nonbio_output_change = rowSums(delta_X[, NONBIO, drop = FALSE]),

        ref_total_GVA = rowSums(REF$GVA),
        scenario_total_GVA = rowSums(scenario$GVA),
        total_GVA_change = rowSums(delta_GVA),
        bio_GVA_change = rowSums(delta_GVA[, BIO, drop = FALSE]),
        nonbio_GVA_change = rowSums(delta_GVA[, NONBIO, drop = FALSE])
      )
    }
  )

  do.call(rbind, out)
}

annual_macro_path <- calculate_annual_macro_path(dynamic_results)
rownames(annual_macro_path) <- NULL

# ===================================================================
# 8. SECTOR-LEVEL OUTPUT AND GVA EFFECTS
# ===================================================================

calculate_sector_changes <- function(year_results, year) {
  REF <- year_results$REF

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- year_results[[scenario_name]]

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        sector_id = seq_along(sector_names),
        sector = sector_names,
        is_biofuel = seq_along(sector_names) %in% BIO,

        output_REF = REF$X,
        output_scenario = scenario$X,
        output_change = scenario$X - REF$X,
        output_change_pct =
          100 * safe_ratio(scenario$X - REF$X, REF$X),

        GVA_REF = REF$GVA,
        GVA_scenario = scenario$GVA,
        GVA_change = scenario$GVA - REF$GVA,
        GVA_change_pct =
          100 * safe_ratio(scenario$GVA - REF$GVA, REF$GVA)
      )
    }
  )

  do.call(rbind, out)
}

sector_changes_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_sector_changes(results[[year]], year)
  )
)
rownames(sector_changes_all) <- NULL

NONBIO_sector_changes_all <- subset(sector_changes_all, !is_biofuel)

get_top_sectors <- function(year, scenario, variable = "output_change", n = 10,
                            nonbio_only = TRUE, decreasing = TRUE) {
  x <- if (nonbio_only) NONBIO_sector_changes_all else sector_changes_all

  x <- x[
    x$year == year & x$scenario == scenario,
  ]

  x <- x[order(x[[variable]], decreasing = decreasing), ]
  x$rank <- seq_len(nrow(x))
  head(x, n)
}

top_NONBIO_output_gains_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      do.call(
        rbind,
        lapply(
          scenario_names,
          function(scenario_name) {
            get_top_sectors(
              year = as.integer(year),
              scenario = scenario_name,
              variable = "output_change",
              n = 10,
              nonbio_only = TRUE,
              decreasing = TRUE
            )
          }
        )
      )
    }
  )
)
rownames(top_NONBIO_output_gains_all) <- NULL

top_NONBIO_GVA_gains_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      do.call(
        rbind,
        lapply(
          scenario_names,
          function(scenario_name) {
            get_top_sectors(
              year = as.integer(year),
              scenario = scenario_name,
              variable = "GVA_change",
              n = 10,
              nonbio_only = TRUE,
              decreasing = TRUE
            )
          }
        )
      )
    }
  )
)
rownames(top_NONBIO_GVA_gains_all) <- NULL

# ===================================================================
# 9. CAPEX ANALYSIS
# ===================================================================

calculate_capex_summary <- function(year_results, year) {
  REF <- year_results$REF

  ref_dom_level <- sum(REF$GFCF_capex_level[NONBIO])
  ref_imp_level <- sum(REF$CAPEX_imp_leakage[NONBIO])

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- year_results[[scenario_name]]

      dom_level <- sum(scenario$GFCF_capex_level[NONBIO])
      dom_delta <- sum(scenario$GFCF_capex_delta[NONBIO])
      imp_level <- sum(scenario$CAPEX_imp_leakage[NONBIO])
      imp_delta <- imp_level - ref_imp_level

      total_level <- dom_level + imp_level
      total_delta <- dom_delta + imp_delta

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,

        domestic_CAPEX_level = dom_level,
        domestic_CAPEX_delta_vs_2023 = dom_delta,
        imported_CAPEX_level = imp_level,
        imported_CAPEX_delta_vs_2023 = imp_delta,
        total_CAPEX_level = total_level,
        total_CAPEX_delta_vs_2023 = total_delta,

        domestic_CAPEX_share = safe_ratio(dom_level, total_level),
        imported_CAPEX_share = safe_ratio(imp_level, total_level),

        REF_domestic_CAPEX_level = ref_dom_level,
        REF_imported_CAPEX_level = ref_imp_level
      )
    }
  )

  do.call(rbind, out)
}

capex_summary_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_capex_summary(results[[year]], year)
  )
)
rownames(capex_summary_all) <- NULL

calculate_annual_capex_path <- function(dynamic_results) {
  REF <- dynamic_results$REF

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- dynamic_results[[scenario_name]]

      dom_level <- rowSums(scenario$GFCF_capex_level[, NONBIO, drop = FALSE])
      dom_delta <- rowSums(scenario$GFCF_capex_delta[, NONBIO, drop = FALSE])
      imp_level <- rowSums(scenario$CAPEX_imp_leakage[, NONBIO, drop = FALSE])
      ref_imp   <- rowSums(REF$CAPEX_imp_leakage[, NONBIO, drop = FALSE])
      imp_delta <- imp_level - ref_imp

      data.frame(
        year = scenario$years,
        scenario = scenario_name,
        domestic_CAPEX_level = dom_level,
        domestic_CAPEX_delta_vs_2023 = dom_delta,
        imported_CAPEX_level = imp_level,
        imported_CAPEX_delta_vs_2023 = imp_delta,
        total_CAPEX_level = dom_level + imp_level,
        total_CAPEX_delta_vs_2023 = dom_delta + imp_delta,
        imported_CAPEX_share = safe_ratio(imp_level, dom_level + imp_level)
      )
    }
  )

  do.call(rbind, out)
}

annual_capex_path <- calculate_annual_capex_path(dynamic_results)
rownames(annual_capex_path) <- NULL

# ===================================================================
# 10. IMPORT DEPENDENCE AND BIOFUEL TRADE
# ===================================================================

calculate_import_trade_summary <- function(year_results, year) {
  REF <- year_results$REF

  ref_dom_rec <- as.numeric(get_domestic_recurrent_demand(REF))
  ref_imp_rec <- as.numeric(get_imported_recurrent_demand(REF))
  ref_finished_imports <- sum(REF$Y_imp_FCE[BIO])
  ref_exports <- sum(REF$exports[BIO])

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- year_results[[scenario_name]]

      dom_rec <- as.numeric(get_domestic_recurrent_demand(scenario))
      imp_rec <- as.numeric(get_imported_recurrent_demand(scenario))

      dom_cap <- as.numeric(get_domestic_capex_level_from_coefficients(scenario))
      imp_cap <- as.numeric(get_imported_capex_level_from_coefficients(scenario))

      recurrent_domestic <- sum(dom_rec)
      recurrent_imported <- sum(imp_rec)
      recurrent_total <- recurrent_domestic + recurrent_imported

      capex_domestic <- sum(dom_cap)
      capex_imported <- sum(imp_cap)
      capex_total <- capex_domestic + capex_imported

      finished_imports <- sum(scenario$Y_imp_FCE[BIO])
      exports <- sum(scenario$exports[BIO])

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,

        recurrent_domestic_input_level = recurrent_domestic,
        recurrent_imported_input_level = recurrent_imported,
        recurrent_import_share =
          safe_ratio(recurrent_imported, recurrent_total),
        recurrent_import_change_vs_REF =
          recurrent_imported - sum(ref_imp_rec),

        domestic_CAPEX_input_level = capex_domestic,
        imported_CAPEX_input_level = capex_imported,
        CAPEX_import_share =
          safe_ratio(capex_imported, capex_total),
        imported_CAPEX_change_vs_REF =
          capex_imported - sum(get_imported_capex_level_from_coefficients(REF)),

        finished_biofuel_imports = finished_imports,
        finished_biofuel_import_change_vs_REF =
          finished_imports - ref_finished_imports,

        biofuel_exports = exports,
        biofuel_export_change_vs_REF =
          exports - ref_exports,

        net_finished_biofuel_imports =
          finished_imports - exports,

        recurrent_domestic_input_change_vs_REF =
          recurrent_domestic - sum(ref_dom_rec)
      )
    }
  )

  do.call(rbind, out)
}

import_trade_summary_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_import_trade_summary(results[[year]], year)
  )
)
rownames(import_trade_summary_all) <- NULL

# Annual import/trade path
calculate_annual_import_trade_path <- function(dynamic_results) {
  REF <- dynamic_results$REF

  out <- list()
  counter <- 1

  for (scenario_name in scenario_names) {
    scenario <- dynamic_results[[scenario_name]]

    for (i in seq_along(scenario$years)) {
      year_char <- as.character(scenario$years[i])

      # Reconstruct a lightweight endpoint from annual arrays.
      s <- list(
        A_dom_tech = scenario$A_dom_tech[year_char, , ],
        A_imp_tech = scenario$A_imp_tech[year_char, , ],
        A_capex_dom_tech = scenario$A_capex_dom_tech[year_char, , ],
        A_capex_imp_tech = scenario$A_capex_imp_tech[year_char, , ],
        X_bio = scenario$X_bio[year_char, ],
        Y_imp_FCE = scenario$Y_imp_FCE[year_char, ],
        exports = scenario$exports[year_char, ]
      )

      r <- list(
        A_dom_tech = REF$A_dom_tech[year_char, , ],
        A_imp_tech = REF$A_imp_tech[year_char, , ],
        A_capex_dom_tech = REF$A_capex_dom_tech[year_char, , ],
        A_capex_imp_tech = REF$A_capex_imp_tech[year_char, , ],
        X_bio = REF$X_bio[year_char, ],
        Y_imp_FCE = REF$Y_imp_FCE[year_char, ],
        exports = REF$exports[year_char, ]
      )

      dom_rec <- sum(get_domestic_recurrent_demand(s))
      imp_rec <- sum(get_imported_recurrent_demand(s))
      dom_cap <- sum(get_domestic_capex_level_from_coefficients(s))
      imp_cap <- sum(get_imported_capex_level_from_coefficients(s))

      ref_imp_rec <- sum(get_imported_recurrent_demand(r))
      ref_imp_cap <- sum(get_imported_capex_level_from_coefficients(r))
      ref_finished_imports <- sum(r$Y_imp_FCE[BIO])
      ref_exports <- sum(r$exports[BIO])

      finished_imports <- sum(s$Y_imp_FCE[BIO])
      exports <- sum(s$exports[BIO])

      out[[counter]] <- data.frame(
        year = scenario$years[i],
        scenario = scenario_name,
        recurrent_domestic_input_level = dom_rec,
        recurrent_imported_input_level = imp_rec,
        recurrent_import_share = safe_ratio(imp_rec, dom_rec + imp_rec),
        recurrent_import_change_vs_REF = imp_rec - ref_imp_rec,
        domestic_CAPEX_input_level = dom_cap,
        imported_CAPEX_input_level = imp_cap,
        CAPEX_import_share = safe_ratio(imp_cap, dom_cap + imp_cap),
        imported_CAPEX_change_vs_REF = imp_cap - ref_imp_cap,
        finished_biofuel_imports = finished_imports,
        finished_biofuel_import_change_vs_REF =
          finished_imports - ref_finished_imports,
        biofuel_exports = exports,
        biofuel_export_change_vs_REF = exports - ref_exports,
        net_finished_biofuel_imports = finished_imports - exports
      )

      counter <- counter + 1
    }
  }

  do.call(rbind, out)
}

annual_import_trade_path <- calculate_annual_import_trade_path(dynamic_results)
rownames(annual_import_trade_path) <- NULL

# ===================================================================
# 11. NONBIO OUTPUT DECOMPOSITION:
#     RECURRENT DIRECT + CAPEX DIRECT + HIGHER-ORDER
# ===================================================================

decompose_NONBIO_output <- function(scenario, ref) {
  A_NN_ref <- ref$A_dom_tech[NONBIO, NONBIO, drop = FALSE]

  stopifnot(
    isTRUE(
      all.equal(
        scenario$A_dom_tech[NONBIO, NONBIO, drop = FALSE],
        A_NN_ref,
        tolerance = 1e-10
      )
    )
  )

  L_NN <- solve(
    base::diag(length(NONBIO)) - A_NN_ref
  )

  recurrent_scenario <-
    scenario$A_dom_tech[NONBIO, BIO, drop = FALSE] %*%
    scenario$X_bio[BIO]

  recurrent_ref <-
    ref$A_dom_tech[NONBIO, BIO, drop = FALSE] %*%
    ref$X_bio[BIO]

  recurrent_shock <- recurrent_scenario - recurrent_ref

  capex_shock <-
    scenario$GFCF_capex_delta[NONBIO] -
    ref$GFCF_capex_delta[NONBIO]

  direct_shock <-
    as.numeric(recurrent_shock) +
    as.numeric(capex_shock)

  recurrent_total_effect <-
    as.numeric(L_NN %*% recurrent_shock)

  capex_total_effect <-
    as.numeric(L_NN %*% capex_shock)

  reconstructed_total_effect <-
    recurrent_total_effect + capex_total_effect

  actual_total_effect <-
    scenario$X[NONBIO] - ref$X[NONBIO]

  stopifnot(
    isTRUE(
      all.equal(
        reconstructed_total_effect,
        as.numeric(actual_total_effect),
        tolerance = 1e-8
      )
    )
  )

  data.frame(
    recurrent_first_order_output = sum(recurrent_shock),
    capex_first_order_output = sum(capex_shock),
    total_first_order_output = sum(direct_shock),

    recurrent_higher_order_output =
      sum(recurrent_total_effect) - sum(recurrent_shock),
    capex_higher_order_output =
      sum(capex_total_effect) - sum(capex_shock),
    total_higher_order_output =
      sum(reconstructed_total_effect) - sum(direct_shock),

    recurrent_total_NONBIO_output = sum(recurrent_total_effect),
    capex_total_NONBIO_output = sum(capex_total_effect),
    total_NONBIO_output = sum(actual_total_effect)
  )
}

calculate_NONBIO_decomposition <- function(year_results, year) {
  REF <- year_results$REF

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      d <- decompose_NONBIO_output(year_results[[scenario_name]], REF)

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        d
      )
    }
  )

  
  do.call(rbind, out)
}

NONBIO_decomposition_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_NONBIO_decomposition(results[[year]], year)
  )
)
rownames(NONBIO_decomposition_all) <- NULL

# Shares and activation ratios
NONBIO_decomposition_all$recurrent_share_NONBIO <-
  safe_ratio(
    NONBIO_decomposition_all$recurrent_total_NONBIO_output,
    NONBIO_decomposition_all$total_NONBIO_output
  )

NONBIO_decomposition_all$capex_share_NONBIO <-
  safe_ratio(
    NONBIO_decomposition_all$capex_total_NONBIO_output,
    NONBIO_decomposition_all$total_NONBIO_output
  )

NONBIO_decomposition_all$first_order_share_NONBIO <-
  safe_ratio(
    NONBIO_decomposition_all$total_first_order_output,
    NONBIO_decomposition_all$total_NONBIO_output
  )

NONBIO_decomposition_all$higher_order_share_NONBIO <-
  safe_ratio(
    NONBIO_decomposition_all$total_higher_order_output,
    NONBIO_decomposition_all$total_NONBIO_output
  )

activation_summary_all <- merge(
  NONBIO_decomposition_all,
  macro_summary_all[
    ,
    c(
      "year",
      "scenario",
      "bio_output_change",
      "nonbio_output_change",
      "total_GVA_change",
      "nonbio_GVA_change"
    )
  ],
  by = c("year", "scenario")
)

activation_summary_all$NONBIO_output_per_eur_BIO_output_change <-
  safe_ratio(
    activation_summary_all$nonbio_output_change,
    activation_summary_all$bio_output_change
  )

activation_summary_all$GVA_change_per_eur_BIO_output_change <-
  safe_ratio(
    activation_summary_all$total_GVA_change,
    activation_summary_all$bio_output_change
  )

activation_summary_all$NONBIO_GVA_change_per_eur_BIO_output_change <-
  safe_ratio(
    activation_summary_all$nonbio_GVA_change,
    activation_summary_all$bio_output_change
  )

# ===================================================================
# 11B. SCENARIO-INTERNAL UPSTREAM OUTPUT STRUCTURE
#      FEEDSTOCK / OPEX / CAPEX
#
# This is NOT a scenario-vs-REF decomposition.
# It measures the absolute domestic upstream NONBIO output requirements
# associated with the technology and production structure of S1/S2/S3.
#
# CAPEX is therefore used at its absolute annualized level, NOT as
# GFCF_capex_delta relative to 2023.
# ===================================================================


calculate_channel_output_structure <- function(
    scenario,
    year,
    scenario_name
) {

  # ---------------------------------------------------------------
  # NONBIO production structure
  # ---------------------------------------------------------------

  A_NN <-
    scenario$A_dom_tech[
      NONBIO,
      NONBIO,
      drop = FALSE
    ]

  L_NN <-
    solve(
      base::diag(length(NONBIO)) -
        A_NN
    )


  # ---------------------------------------------------------------
  # 1. DIRECT FEEDSTOCK-DRIVEN NONBIO DEMAND
  # ---------------------------------------------------------------

  feedstock_direct <-
    scenario$A_feed_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]


  # ---------------------------------------------------------------
  # 2. DIRECT OPEX-DRIVEN NONBIO DEMAND
  # ---------------------------------------------------------------

  opex_direct <-
    scenario$A_opex_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]


  # ---------------------------------------------------------------
  # 3. DIRECT CAPEX-DRIVEN NONBIO DEMAND
  #
  # IMPORTANT:
  # absolute annualized CAPEX level, NOT delta vs 2023
  # ---------------------------------------------------------------

  capex_direct <-
    scenario$A_capex_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]


  # ---------------------------------------------------------------
  # CHECK:
  # Feedstock + OPEX must reproduce recurrent BIO-driven demand
  # ---------------------------------------------------------------

  recurrent_direct <-
    scenario$A_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]

  stopifnot(
    isTRUE(
      all.equal(
        as.numeric(feedstock_direct + opex_direct),
        as.numeric(recurrent_direct),
        tolerance = 1e-10
      )
    )
  )


  # ---------------------------------------------------------------
  # PROPAGATE THROUGH NONBIO SUPPLY CHAINS
  # ---------------------------------------------------------------

  feedstock_total <-
    as.numeric(
      L_NN %*%
        feedstock_direct
    )

  opex_total <-
    as.numeric(
      L_NN %*%
        opex_direct
    )

  capex_total <-
    as.numeric(
      L_NN %*%
        capex_direct
    )


  # ---------------------------------------------------------------
  # FIRST-ORDER VALUES
  # ---------------------------------------------------------------

  feedstock_first <-
    as.numeric(feedstock_direct)

  opex_first <-
    as.numeric(opex_direct)

  capex_first <-
    as.numeric(capex_direct)


  # ---------------------------------------------------------------
  # HIGHER-ORDER VALUES
  # ---------------------------------------------------------------

  feedstock_higher <-
    feedstock_total -
    feedstock_first

  opex_higher <-
    opex_total -
    opex_first

  capex_higher <-
    capex_total -
    capex_first


  # ---------------------------------------------------------------
  # AGGREGATE OUTPUT REQUIREMENTS
  # ---------------------------------------------------------------

  feedstock_output <-
    sum(feedstock_total)

  opex_output <-
    sum(opex_total)

  capex_output <-
    sum(capex_total)

  total_upstream_output <-
    feedstock_output +
    opex_output +
    capex_output


  # Domestic BIO production level
  total_bio_output <-
    sum(
      scenario$X_bio[BIO]
    )


  # ---------------------------------------------------------------
  # RETURN AGGREGATE RESULT
  # ---------------------------------------------------------------

  data.frame(

    year = as.integer(year),

    scenario = scenario_name,

    BIO_output_level =
      total_bio_output,


    # First-order activation
    feedstock_first_order_output =
      sum(feedstock_first),

    opex_first_order_output =
      sum(opex_first),

    capex_first_order_output =
      sum(capex_first),


    # Higher-order activation
    feedstock_higher_order_output =
      sum(feedstock_higher),

    opex_higher_order_output =
      sum(opex_higher),

    capex_higher_order_output =
      sum(capex_higher),


    # Total upstream output requirement
    feedstock_total_output =
      feedstock_output,

    opex_total_output =
      opex_output,

    capex_total_output =
      capex_output,

    total_upstream_output =
      total_upstream_output,


    # Composition shares
    feedstock_share =
      safe_ratio(
        feedstock_output,
        total_upstream_output
      ),

    opex_share =
      safe_ratio(
        opex_output,
        total_upstream_output
      ),

    capex_share =
      safe_ratio(
        capex_output,
        total_upstream_output
      ),


    # Output requirement per EUR of domestic BIO output
    feedstock_output_per_eur_BIO =
      safe_ratio(
        feedstock_output,
        total_bio_output
      ),

    opex_output_per_eur_BIO =
      safe_ratio(
        opex_output,
        total_bio_output
      ),

    capex_output_per_eur_BIO =
      safe_ratio(
        capex_output,
        total_bio_output
      ),

    total_upstream_output_per_eur_BIO =
      safe_ratio(
        total_upstream_output,
        total_bio_output
      )
  )
}


channel_output_structure_all <-
  do.call(
    rbind,
    lapply(
      benchmark_years,
      function(year) {

        do.call(
          rbind,
          lapply(
            scenario_names,
            function(scenario_name) {

              calculate_channel_output_structure(
                scenario =
                  results[[year]][[scenario_name]],

                year = year,

                scenario_name =
                  scenario_name
              )
            }
          )
        )
      }
    )
  )

rownames(
  channel_output_structure_all
) <- NULL

stopifnot(

  abs(
    channel_output_structure_all$feedstock_share +
      channel_output_structure_all$opex_share +
      channel_output_structure_all$capex_share -
      1
  ) < 1e-10
)



calculate_channel_sector_structure <- function(
    scenario,
    year,
    scenario_name
) {

  A_NN <-
    scenario$A_dom_tech[
      NONBIO,
      NONBIO,
      drop = FALSE
    ]

  L_NN <-
    solve(
      base::diag(length(NONBIO)) -
        A_NN
    )


  feedstock_direct <-
    scenario$A_feed_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]

  opex_direct <-
    scenario$A_opex_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]

  capex_direct <-
    scenario$A_capex_dom_tech[
      NONBIO,
      BIO,
      drop = FALSE
    ] %*%
    scenario$X_bio[BIO]


  feedstock_total <-
    as.numeric(
      L_NN %*%
        feedstock_direct
    )

  opex_total <-
    as.numeric(
      L_NN %*%
        opex_direct
    )

  capex_total <-
    as.numeric(
      L_NN %*%
        capex_direct
    )


  data.frame(

    year = as.integer(year),

    scenario = scenario_name,

    sector_id = NONBIO,

    sector =
      sector_names[NONBIO],

    feedstock_driven_output =
      feedstock_total,

    opex_driven_output =
      opex_total,

    capex_driven_output =
      capex_total,

    total_upstream_output =
      feedstock_total +
      opex_total +
      capex_total
  )
}

channel_sector_structure_all <-
  do.call(
    rbind,
    lapply(
      benchmark_years,
      function(year) {

        do.call(
          rbind,
          lapply(
            scenario_names,
            function(scenario_name) {

              calculate_channel_sector_structure(
                scenario =
                  results[[year]][[scenario_name]],

                year = year,

                scenario_name =
                  scenario_name
              )
            }
          )
        )
      }
    )
  )

rownames(
  channel_sector_structure_all
) <- NULL

# ===================================================================
# 12. DIRECT INPUT INTENSITY BY BIOFUEL
#     RECURRENT / CAPEX / IMPORTED
# ===================================================================

calculate_biofuel_input_intensity <- function(year_results, year) {
  out <- list()
  counter <- 1

  for (scenario_name in scenario_names) {
    scenario <- year_results[[scenario_name]]

    for (bio_sector in BIO) {
      recurrent_dom_all <-
        sum(scenario$A_dom_tech[, bio_sector])

      recurrent_dom_NONBIO <-
        sum(scenario$A_dom_tech[NONBIO, bio_sector])

      recurrent_imp <-
        sum(scenario$A_imp_tech[, bio_sector])

      capex_dom_all <-
        sum(scenario$A_capex_dom_tech[, bio_sector])

      capex_dom_NONBIO <-
        sum(scenario$A_capex_dom_tech[NONBIO, bio_sector])

      capex_imp <-
        sum(scenario$A_capex_imp_tech[, bio_sector])

      total_dom_all <- recurrent_dom_all + capex_dom_all
      total_imp <- recurrent_imp + capex_imp

      out[[counter]] <- data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        bio_sector_id = bio_sector,
        biofuel = get_fuel_name(bio_sector),
        fuel_group = get_fuel_group(bio_sector),

        recurrent_domestic_all_intensity = recurrent_dom_all,
        recurrent_domestic_NONBIO_intensity = recurrent_dom_NONBIO,
        recurrent_import_intensity = recurrent_imp,

        capex_domestic_all_intensity = capex_dom_all,
        capex_domestic_NONBIO_intensity = capex_dom_NONBIO,
        capex_import_intensity = capex_imp,

        total_domestic_all_intensity = total_dom_all,
        total_domestic_NONBIO_intensity =
          recurrent_dom_NONBIO + capex_dom_NONBIO,
        total_import_intensity = total_imp,

        direct_input_import_share =
          safe_ratio(total_imp, total_dom_all + total_imp)
      )

      counter <- counter + 1
    }
  }

  do.call(rbind, out)
}

biofuel_input_intensity_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) calculate_biofuel_input_intensity(results[[year]], year)
  )
)
rownames(biofuel_input_intensity_all) <- NULL

advanced_biofuel_input_intensity_all <-
  subset(biofuel_input_intensity_all, fuel_group == "advanced")

# ===================================================================
# 13. BIOFUEL-SPECIFIC CONTRIBUTION TO NONBIO OUTPUT
#     INCLUDING RECURRENT, CAPEX AND HIGHER-ORDER EFFECTS
# ===================================================================

calculate_biofuel_NONBIO_contributions <- function(year_results, year) {
  REF <- year_results$REF

  A_NN_ref <- REF$A_dom_tech[NONBIO, NONBIO, drop = FALSE]
  L_NN <- solve(base::diag(length(NONBIO)) - A_NN_ref)

  out <- list()
  counter <- 1

  for (scenario_name in scenario_names) {
    scenario <- year_results[[scenario_name]]

    stopifnot(
      isTRUE(
        all.equal(
          scenario$A_dom_tech[NONBIO, NONBIO, drop = FALSE],
          A_NN_ref,
          tolerance = 1e-10
        )
      )
    )

    for (bio_sector in BIO) {
      recurrent_shock <-
        scenario$A_dom_tech[NONBIO, bio_sector] *
          scenario$X_bio[bio_sector] -
        REF$A_dom_tech[NONBIO, bio_sector] *
          REF$X_bio[bio_sector]

      capex_shock <-
        scenario$A_capex_dom_tech[NONBIO, bio_sector] *
          scenario$X_bio[bio_sector] -
        REF$A_capex_dom_tech[NONBIO, bio_sector] *
          REF$X_bio[bio_sector]

      recurrent_total <-
        as.numeric(L_NN %*% recurrent_shock)

      capex_total <-
        as.numeric(L_NN %*% capex_shock)

      total_effect <- recurrent_total + capex_total

      out[[counter]] <- data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        bio_sector_id = bio_sector,
        biofuel = get_fuel_name(bio_sector),
        fuel_group = get_fuel_group(bio_sector),

        fuel_market_value_REF = REF$X_bio[bio_sector],
        fuel_market_value_scenario = scenario$X_bio[bio_sector],
        fuel_market_value_change =
          scenario$X_bio[bio_sector] - REF$X_bio[bio_sector],

        recurrent_first_order_contribution = sum(recurrent_shock),
        capex_first_order_contribution = sum(capex_shock),
        first_order_contribution =
          sum(recurrent_shock) + sum(capex_shock),

        recurrent_higher_order_contribution =
          sum(recurrent_total) - sum(recurrent_shock),
        capex_higher_order_contribution =
          sum(capex_total) - sum(capex_shock),
        higher_order_contribution =
          sum(total_effect) -
          sum(recurrent_shock) -
          sum(capex_shock),

        recurrent_total_NONBIO_contribution = sum(recurrent_total),
        capex_total_NONBIO_contribution = sum(capex_total),
        total_NONBIO_contribution = sum(total_effect)
      )

      counter <- counter + 1
    }


    
  }

  do.call(rbind, out)
}

biofuel_NONBIO_contributions_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      calculate_biofuel_NONBIO_contributions(results[[year]], year)
    }
  )
)
rownames(biofuel_NONBIO_contributions_all) <- NULL

# Add total NONBIO output change and contribution shares.
biofuel_NONBIO_contributions_all <- merge(
  biofuel_NONBIO_contributions_all,
  macro_summary_all[, c("year", "scenario", "nonbio_output_change")],
  by = c("year", "scenario")
)

biofuel_NONBIO_contributions_all$contribution_share_total_NONBIO <-
  safe_ratio(
    biofuel_NONBIO_contributions_all$total_NONBIO_contribution,
    biofuel_NONBIO_contributions_all$nonbio_output_change
  )

# Contributions of all BIO sectors together must reproduce the actual
# NONBIO output change from the model.
contribution_check <- aggregate(
  total_NONBIO_contribution ~ year + scenario,
  data = biofuel_NONBIO_contributions_all,
  FUN = sum
)

contribution_check <- merge(
  contribution_check,
  macro_summary_all[, c("year", "scenario", "nonbio_output_change")],
  by = c("year", "scenario")
)

stopifnot(
  isTRUE(
    all.equal(
      contribution_check$total_NONBIO_contribution,
      contribution_check$nonbio_output_change,
      tolerance = 1e-8
    )
  )
)

# ===================================================================
# 14. FUEL-GROUP SUMMARY: ADVANCED / CONVENTIONAL / RFNBO
# ===================================================================

fuel_group_contributions_all <- aggregate(
  cbind(
    fuel_market_value_REF,
    fuel_market_value_scenario,
    fuel_market_value_change,
    recurrent_first_order_contribution,
    capex_first_order_contribution,
    first_order_contribution,
    recurrent_higher_order_contribution,
    capex_higher_order_contribution,
    higher_order_contribution,
    recurrent_total_NONBIO_contribution,
    capex_total_NONBIO_contribution,
    total_NONBIO_contribution
  ) ~ year + scenario + fuel_group,
  data = biofuel_NONBIO_contributions_all,
  FUN = sum
)

fuel_group_contributions_all$NONBIO_output_per_eur_fuel_change <-
  safe_ratio(
    fuel_group_contributions_all$total_NONBIO_contribution,
    fuel_group_contributions_all$fuel_market_value_change
  )

fuel_group_contributions_all$capex_share_of_attributed_NONBIO <-
  safe_ratio(
    fuel_group_contributions_all$capex_total_NONBIO_contribution,
    fuel_group_contributions_all$total_NONBIO_contribution
  )

advanced_biofuel_contributions_all <-
  subset(biofuel_NONBIO_contributions_all, fuel_group == "advanced")

advanced_group_summary_all <-
  subset(fuel_group_contributions_all, fuel_group == "advanced")

# Advanced-fuel-specific shares within the advanced contribution only.
advanced_total_by_scenario <- aggregate(
  total_NONBIO_contribution ~ year + scenario,
  data = advanced_biofuel_contributions_all,
  FUN = sum
)
names(advanced_total_by_scenario)[3] <- "advanced_total_NONBIO"

advanced_biofuel_contributions_all <- merge(
  advanced_biofuel_contributions_all,
  advanced_total_by_scenario,
  by = c("year", "scenario")
)

advanced_biofuel_contributions_all$advanced_contribution_share <-
  safe_ratio(
    advanced_biofuel_contributions_all$total_NONBIO_contribution,
    advanced_biofuel_contributions_all$advanced_total_NONBIO
  )

# ===================================================================
# 15. NONBIO SECTOR EFFECTS ATTRIBUTABLE TO ADVANCED BIOFUELS
# ===================================================================

calculate_advanced_NONBIO_sector_effects <- function(year_results, year) {
  REF <- year_results$REF
  A_NN <- REF$A_dom_tech[NONBIO, NONBIO, drop = FALSE]
  L_NN <- solve(base::diag(length(NONBIO)) - A_NN)

  out <- lapply(
    scenario_names,
    function(scenario_name) {
      scenario <- year_results[[scenario_name]]

      recurrent_scenario <-
        scenario$A_dom_tech[NONBIO, ADV_BIO, drop = FALSE] %*%
        scenario$X_bio[ADV_BIO]

      recurrent_ref <-
        REF$A_dom_tech[NONBIO, ADV_BIO, drop = FALSE] %*%
        REF$X_bio[ADV_BIO]

      capex_scenario <-
        scenario$A_capex_dom_tech[NONBIO, ADV_BIO, drop = FALSE] %*%
        scenario$X_bio[ADV_BIO]

      capex_ref <-
        REF$A_capex_dom_tech[NONBIO, ADV_BIO, drop = FALSE] %*%
        REF$X_bio[ADV_BIO]

      recurrent_shock <- as.numeric(recurrent_scenario - recurrent_ref)
      capex_shock <- as.numeric(capex_scenario - capex_ref)
      direct_shock <- recurrent_shock + capex_shock

      recurrent_total <- as.numeric(L_NN %*% recurrent_shock)
      capex_total <- as.numeric(L_NN %*% capex_shock)
      total_effect <- recurrent_total + capex_total

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        sector_id = NONBIO,
        sector = sector_names[NONBIO],

        advanced_recurrent_first_order_effect = recurrent_shock,
        advanced_capex_first_order_effect = capex_shock,
        advanced_first_order_effect = direct_shock,

        advanced_recurrent_total_effect = recurrent_total,
        advanced_capex_total_effect = capex_total,
        advanced_total_output_effect = total_effect,

        advanced_higher_order_effect = total_effect - direct_shock
      )
    }
  )

  do.call(rbind, out)
}

advanced_NONBIO_sector_effects_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      calculate_advanced_NONBIO_sector_effects(results[[year]], year)
    }
  )
)
rownames(advanced_NONBIO_sector_effects_all) <- NULL

get_top_advanced_NONBIO_sectors <- function(year, scenario, n = 10) {
  x <- advanced_NONBIO_sector_effects_all[
    advanced_NONBIO_sector_effects_all$year == year &
      advanced_NONBIO_sector_effects_all$scenario == scenario,
  ]

  x <- x[order(x$advanced_total_output_effect, decreasing = TRUE), ]
  x$rank <- seq_len(nrow(x))
  head(x, n)
}

top_advanced_NONBIO_sectors_all <- do.call(
  rbind,
  lapply(
    benchmark_years,
    function(year) {
      do.call(
        rbind,
        lapply(
          scenario_names,
          function(scenario_name) {
            get_top_advanced_NONBIO_sectors(
              year = as.integer(year),
              scenario = scenario_name,
              n = 10
            )
          }
        )
      )
    }
  )
)
rownames(top_advanced_NONBIO_sectors_all) <- NULL

# ===================================================================
# 16. S2 VS S3: SYMMETRIC SCALE / RECURRENT-TECH / CAPEX-TECH DECOMPOSITION
# ===================================================================
#
# For NONBIO output:
#   X_N = L_NN [Y_base + A_rec X_B + A_cap X_B - K_2023]
#
# Between S2 and S3, Y_base and K_2023 cancel. We use the exact
# symmetric decomposition:
#
# A3 x3 - A2 x2 =
#   0.5 (A2 + A3)(x3 - x2)          [scale]
# + 0.5 (A3 - A2)(x3 + x2)          [technology]
#
# and split technology into recurrent and CAPEX coefficient effects.
# ===================================================================

calculate_S2_S3_decomposition <- function(year_results, year) {
  S2 <- year_results$S2
  S3 <- year_results$S3

  A_NN <- S2$A_dom_tech[NONBIO, NONBIO, drop = FALSE]

  stopifnot(
    isTRUE(
      all.equal(
        A_NN,
        S3$A_dom_tech[NONBIO, NONBIO, drop = FALSE],
        tolerance = 1e-10
      )
    )
  )

  L_NN <- solve(base::diag(length(NONBIO)) - A_NN)

  Arec2 <- S2$A_dom_tech[NONBIO, BIO, drop = FALSE]
  Arec3 <- S3$A_dom_tech[NONBIO, BIO, drop = FALSE]

  Acap2 <- S2$A_capex_dom_tech[NONBIO, BIO, drop = FALSE]
  Acap3 <- S3$A_capex_dom_tech[NONBIO, BIO, drop = FALSE]

  x2 <- S2$X_bio[BIO]
  x3 <- S3$X_bio[BIO]

  scale_direct <-
    0.5 * (
      (Arec2 + Acap2) +
      (Arec3 + Acap3)
    ) %*% (x3 - x2)

  recurrent_technology_direct <-
    0.5 * (Arec3 - Arec2) %*% (x3 + x2)

  capex_technology_direct <-
    0.5 * (Acap3 - Acap2) %*% (x3 + x2)

  scale_total <- as.numeric(L_NN %*% scale_direct)
  recurrent_technology_total <-
    as.numeric(L_NN %*% recurrent_technology_direct)
  capex_technology_total <-
    as.numeric(L_NN %*% capex_technology_direct)

  reconstructed_difference <-
    scale_total +
    recurrent_technology_total +
    capex_technology_total

  actual_difference <-
    S3$X[NONBIO] - S2$X[NONBIO]

  stopifnot(
    isTRUE(
      all.equal(
        reconstructed_difference,
        as.numeric(actual_difference),
        tolerance = 1e-8
      )
    )
  )

  aggregate_row <- data.frame(
    year = as.integer(year),

    scale_first_order = sum(scale_direct),
    scale_higher_order = sum(scale_total) - sum(scale_direct),
    scale_total_effect = sum(scale_total),

    recurrent_technology_first_order =
      sum(recurrent_technology_direct),
    recurrent_technology_higher_order =
      sum(recurrent_technology_total) -
      sum(recurrent_technology_direct),
    recurrent_technology_total_effect =
      sum(recurrent_technology_total),

    capex_technology_first_order =
      sum(capex_technology_direct),
    capex_technology_higher_order =
      sum(capex_technology_total) -
      sum(capex_technology_direct),
    capex_technology_total_effect =
      sum(capex_technology_total),

    total_S3_minus_S2_NONBIO = sum(actual_difference),
    decomposition_check =
      sum(reconstructed_difference) - sum(actual_difference)
  )

  sector_rows <- data.frame(
    year = as.integer(year),
    sector_id = NONBIO,
    sector = sector_names[NONBIO],
    scale_effect = scale_total,
    recurrent_technology_effect = recurrent_technology_total,
    capex_technology_effect = capex_technology_total,
    reconstructed_S3_minus_S2 = reconstructed_difference,
    actual_S3_minus_S2 = as.numeric(actual_difference)
  )

  list(
    aggregate = aggregate_row,
    sector = sector_rows
  )
}

S2_S3_decomposition_list <- lapply(
  benchmark_years,
  function(year) {
    calculate_S2_S3_decomposition(results[[year]], year)
  }
)

S2_S3_decomposition_all <- do.call(
  rbind,
  lapply(S2_S3_decomposition_list, function(x) x$aggregate)
)
rownames(S2_S3_decomposition_all) <- NULL

S2_S3_sector_decomposition_all <- do.call(
  rbind,
  lapply(S2_S3_decomposition_list, function(x) x$sector)
)
rownames(S2_S3_sector_decomposition_all) <- NULL

stopifnot(
  max(abs(S2_S3_decomposition_all$decomposition_check)) < 1e-8
)

# ===================================================================
# 17. ADDITIONAL BENCHMARK CHECKS
# ===================================================================

# Dynamic path must match saved benchmark endpoints for X and GVA.
for (year in as.integer(benchmark_years)) {
  for (scenario_name in all_scenarios) {
    annual_idx <- which(
      dynamic_results[[scenario_name]]$years == year
    )

    stopifnot(
      isTRUE(
        all.equal(
          dynamic_results[[scenario_name]]$X[annual_idx, ],
          results[[as.character(year)]][[scenario_name]]$X,
          tolerance = 1e-10
        )
      ),
      isTRUE(
        all.equal(
          dynamic_results[[scenario_name]]$GVA[annual_idx, ],
          results[[as.character(year)]][[scenario_name]]$GVA,
          tolerance = 1e-10
        )
      )
    )
  }
}
# ===================================================================
# ADVANCED BIOFUEL-SPECIFIC DOMESTIC GVA INTENSITY
#
# Scenario-internal analysis.
# No comparison with REF.
#
# For each advanced biofuel:
#   - direct BIO GVA
#   - feedstock-driven upstream GVA
#   - OPEX-driven upstream GVA
#   - CAPEX-related upstream GVA
#
# Upstream GVA is obtained by:
#   1) propagating domestic channel-specific demand through L_NN
#   2) applying NONBIO sector-specific GVA/output coefficients
# ===================================================================


calculate_advanced_biofuel_GVA <- function(
    endpoint,
    year,
    scenario_name
) {

  # ---------------------------------------------------------------
  # NONBIO production structure
  # ---------------------------------------------------------------

  A_NN <-
    endpoint$A_dom_tech[
      NONBIO,
      NONBIO,
      drop = FALSE
    ]

  L_NN <-
    solve(
      base::diag(length(NONBIO)) -
        A_NN
    )


  # ---------------------------------------------------------------
  # NONBIO GVA coefficients
  #
  # v_i = GVA_i / X_i
  # ---------------------------------------------------------------

  gva_coeff_NONBIO <-
    safe_ratio(
      endpoint$GVA[NONBIO],
      endpoint$X[NONBIO]
    )

  gva_coeff_NONBIO[
    !is.finite(gva_coeff_NONBIO)
  ] <- 0


  # ---------------------------------------------------------------
  # CALCULATE EACH ADVANCED BIOFUEL SEPARATELY
  # ---------------------------------------------------------------

  out <- lapply(
    ADV_BIO,
    function(bio_sector) {

      bio_output <-
        endpoint$X_bio[bio_sector]


      # If this fuel is not produced in this scenario-year,
      # keep levels at zero and intensities at NA.
      if (
        !is.finite(bio_output) ||
        abs(bio_output) < 1e-12
      ) {

        return(
          data.frame(
            year = as.integer(year),
            scenario = scenario_name,
            bio_sector_id = bio_sector,
            biofuel = get_fuel_name(bio_sector),

            BIO_output = 0,

            direct_BIO_GVA = 0,
            feedstock_upstream_GVA = 0,
            opex_upstream_GVA = 0,
            recurrent_upstream_GVA = 0,
            capex_upstream_GVA = 0,

            operating_chain_GVA = 0,
            total_associated_GVA = 0,

            direct_BIO_GVA_per_eur_BIO = NA_real_,
            feedstock_upstream_GVA_per_eur_BIO = NA_real_,
            opex_upstream_GVA_per_eur_BIO = NA_real_,
            recurrent_upstream_GVA_per_eur_BIO = NA_real_,
            capex_upstream_GVA_per_eur_BIO = NA_real_,

            operating_chain_GVA_per_eur_BIO = NA_real_,
            total_associated_GVA_per_eur_BIO = NA_real_
          )
        )
      }


      # -----------------------------------------------------------
      # DIRECT DOMESTIC DEMAND BY CHANNEL
      # -----------------------------------------------------------

      feedstock_direct <-
        endpoint$A_feed_dom_tech[
          NONBIO,
          bio_sector,
          drop = FALSE
        ] *
        bio_output


      opex_direct <-
        endpoint$A_opex_dom_tech[
          NONBIO,
          bio_sector,
          drop = FALSE
        ] *
        bio_output


      capex_direct <-
        endpoint$A_capex_dom_tech[
          NONBIO,
          bio_sector,
          drop = FALSE
        ] *
        bio_output


      # -----------------------------------------------------------
      # PROPAGATE THROUGH DOMESTIC NONBIO SUPPLY CHAINS
      # -----------------------------------------------------------

      feedstock_output <-
        as.numeric(
          L_NN %*%
            feedstock_direct
        )


      opex_output <-
        as.numeric(
          L_NN %*%
            opex_direct
        )


      capex_output <-
        as.numeric(
          L_NN %*%
            capex_direct
        )


      # -----------------------------------------------------------
      # CONVERT UPSTREAM OUTPUT INTO UPSTREAM GVA
      # -----------------------------------------------------------

      feedstock_upstream_GVA <-
        sum(
          gva_coeff_NONBIO *
            feedstock_output
        )


      opex_upstream_GVA <-
        sum(
          gva_coeff_NONBIO *
            opex_output
        )


      recurrent_upstream_GVA <-
        feedstock_upstream_GVA +
        opex_upstream_GVA


      capex_upstream_GVA <-
        sum(
          gva_coeff_NONBIO *
            capex_output
        )


      # -----------------------------------------------------------
      # DIRECT GVA OF THE ADVANCED BIOFUEL SECTOR ITSELF
      # -----------------------------------------------------------

      direct_BIO_GVA <-
        endpoint$GVA[bio_sector]


      # -----------------------------------------------------------
      # AGGREGATES
      # -----------------------------------------------------------

      operating_chain_GVA <-
        direct_BIO_GVA +
        recurrent_upstream_GVA


      total_associated_GVA <-
        operating_chain_GVA +
        capex_upstream_GVA


      # -----------------------------------------------------------
      # RETURN
      # -----------------------------------------------------------

      data.frame(
        year = as.integer(year),
        scenario = scenario_name,
        bio_sector_id = bio_sector,
        biofuel = get_fuel_name(bio_sector),

        BIO_output = bio_output,

        direct_BIO_GVA =
          direct_BIO_GVA,

        feedstock_upstream_GVA =
          feedstock_upstream_GVA,

        opex_upstream_GVA =
          opex_upstream_GVA,

        recurrent_upstream_GVA =
          recurrent_upstream_GVA,

        capex_upstream_GVA =
          capex_upstream_GVA,

        operating_chain_GVA =
          operating_chain_GVA,

        total_associated_GVA =
          total_associated_GVA,


        direct_BIO_GVA_per_eur_BIO =
          safe_ratio(
            direct_BIO_GVA,
            bio_output
          ),

        feedstock_upstream_GVA_per_eur_BIO =
          safe_ratio(
            feedstock_upstream_GVA,
            bio_output
          ),

        opex_upstream_GVA_per_eur_BIO =
          safe_ratio(
            opex_upstream_GVA,
            bio_output
          ),

        recurrent_upstream_GVA_per_eur_BIO =
          safe_ratio(
            recurrent_upstream_GVA,
            bio_output
          ),

        capex_upstream_GVA_per_eur_BIO =
          safe_ratio(
            capex_upstream_GVA,
            bio_output
          ),

        operating_chain_GVA_per_eur_BIO =
          safe_ratio(
            operating_chain_GVA,
            bio_output
          ),

        total_associated_GVA_per_eur_BIO =
          safe_ratio(
            total_associated_GVA,
            bio_output
          )
      )
    }
  )


  do.call(
    rbind,
    out
  )
}



advanced_biofuel_GVA_all <-
  do.call(
    rbind,
    lapply(
      benchmark_years,
      function(year) {

        do.call(
          rbind,
          lapply(
            scenario_names,
            function(scenario_name) {

              calculate_advanced_biofuel_GVA(
                endpoint =
                  results[[year]][[scenario_name]],

                year =
                  year,

                scenario_name =
                  scenario_name
              )
            }
          )
        )
      }
    )
  )


rownames(
  advanced_biofuel_GVA_all
) <- NULL

# ===================================================================
# AGGREGATE ADVANCED-BIOFUEL GVA INTENSITY
# ===================================================================

advanced_GVA_summary_all <-
  aggregate(
    cbind(
      BIO_output,
      direct_BIO_GVA,
      feedstock_upstream_GVA,
      opex_upstream_GVA,
      recurrent_upstream_GVA,
      capex_upstream_GVA,
      operating_chain_GVA,
      total_associated_GVA
    ) ~ year + scenario,
    data = advanced_biofuel_GVA_all,
    FUN = sum
  )


advanced_GVA_summary_all$direct_BIO_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$direct_BIO_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$feedstock_upstream_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$feedstock_upstream_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$opex_upstream_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$opex_upstream_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$recurrent_upstream_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$recurrent_upstream_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$capex_upstream_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$capex_upstream_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$operating_chain_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$operating_chain_GVA,
    advanced_GVA_summary_all$BIO_output
  )


advanced_GVA_summary_all$total_associated_GVA_per_eur_ADV <-
  safe_ratio(
    advanced_GVA_summary_all$total_associated_GVA,
    advanced_GVA_summary_all$BIO_output
  )
  

  
# ===================================================================
# 18. SAVE ANALYSIS TABLES
# ===================================================================

analysis_tables <- list(
  macro_summary_all = macro_summary_all,
  pairwise_macro_all = pairwise_macro_all,
  annual_macro_path = annual_macro_path,
  sector_changes_all = sector_changes_all,
  top_NONBIO_output_gains_all = top_NONBIO_output_gains_all,
  top_NONBIO_GVA_gains_all = top_NONBIO_GVA_gains_all,
  capex_summary_all = capex_summary_all,
  annual_capex_path = annual_capex_path,
  import_trade_summary_all = import_trade_summary_all,
  annual_import_trade_path = annual_import_trade_path,
  NONBIO_decomposition_all = NONBIO_decomposition_all,
  activation_summary_all = activation_summary_all,
  biofuel_input_intensity_all = biofuel_input_intensity_all,
  advanced_biofuel_input_intensity_all = advanced_biofuel_input_intensity_all,
  biofuel_NONBIO_contributions_all = biofuel_NONBIO_contributions_all,
  fuel_group_contributions_all = fuel_group_contributions_all,
  advanced_biofuel_contributions_all = advanced_biofuel_contributions_all,
  advanced_group_summary_all = advanced_group_summary_all,
  advanced_NONBIO_sector_effects_all = advanced_NONBIO_sector_effects_all,
  top_advanced_NONBIO_sectors_all = top_advanced_NONBIO_sectors_all,
  S2_S3_decomposition_all = S2_S3_decomposition_all,
  S2_S3_sector_decomposition_all = S2_S3_sector_decomposition_all,
  channel_output_structure_all = channel_output_structure_all,
  channel_sector_structure_all = channel_sector_structure_all,
  advanced_biofuel_GVA_all =
  advanced_biofuel_GVA_all,

advanced_GVA_summary_all =
  advanced_GVA_summary_all
)

for (table_name in names(analysis_tables)) {
  write.csv(
    analysis_tables[[table_name]],
    file.path(OUTPUT_DIR, paste0(table_name, ".csv")),
    row.names = FALSE
  )
}

saveRDS(
  analysis_tables,
  file.path(OUTPUT_DIR, "analysis_results_CAPEX_separate.rds")
)

# ===================================================================
# 19. PRINT MAIN RESULTS
# ===================================================================

cat("\n===============================================================\n")
cat("MACRO SUMMARY: OUTPUT AND GVA\n")
cat("===============================================================\n")
print(macro_summary_all)

cat("\n===============================================================\n")
cat("CAPEX SUMMARY\n")
cat("===============================================================\n")
print(capex_summary_all)

cat("\n===============================================================\n")
cat("IMPORT DEPENDENCE / BIOFUEL TRADE\n")
cat("===============================================================\n")
print(import_trade_summary_all)

cat("\n===============================================================\n")
cat("NONBIO ACTIVATION DECOMPOSITION\n")
cat("===============================================================\n")
print(NONBIO_decomposition_all)

cat("\n===============================================================\n")
cat("FUEL-GROUP CONTRIBUTIONS\n")
cat("===============================================================\n")
print(fuel_group_contributions_all)

cat("\n===============================================================\n")
cat("S2 VS S3: SCALE / RECURRENT TECHNOLOGY / CAPEX TECHNOLOGY\n")
cat("===============================================================\n")
print(S2_S3_decomposition_all)

cat("\nAnalysis complete. CSV and RDS outputs written to: ", OUTPUT_DIR, "\n", sep = "")

  cat("\n===============================================================\n")
cat("SCENARIO-INTERNAL FEEDSTOCK / OPEX / CAPEX OUTPUT STRUCTURE\n")
cat("===============================================================\n")

print(
  channel_output_structure_all
)
